ignore:
  - "tasks/**/tests/**"
  - "modules/**/tests/**"
  - "tasks/common/runners/**"
  - "modules/runners/**"
  - "modules/util/include/perf_test_util.hpp"
  - "modules/util/include/func_test_util.hpp"
  - "modules/util/src/func_test_util.cpp"
coverage:
  status:
    project:
      default:
        threshold: 1%
    patch:
      default:
        threshold: 5%
