name: 'Native Clang-Tidy Analysis'
description: 'Run clang-tidy analysis without Docker'
inputs:
  build_dir:
    description: 'Build directory for CMake'
    required: false
    default: 'build'
  exclude:
    description: 'Directories to exclude from analysis'
    required: false
    default: '3rdparty'
  clang_tidy_version:
    description: 'Clang-tidy version to use'
    required: false
    default: '20'
outputs:
  total_comments:
    description: 'Total number of clang-tidy issues found'
    value: ${{ steps.analyze.outputs.total_comments }}
runs:
  using: 'composite'
  steps:
    - name: Verify clang-tidy installation
      shell: bash
      run: |
        clang-tidy-${{ inputs.clang_tidy_version }} --version

    - name: Get changed files
      id: changed-files
      shell: bash
      run: |
        git config --global --add safe.directory $GITHUB_WORKSPACE
        git fetch origin ${{ github.event.pull_request.base.ref }}
        CHANGED_FILES=$(git diff --name-only \
          origin/${{ github.event.pull_request.base.ref }}...HEAD \
          -- '*.cpp' '*.hpp' '*.c' '*.h' | grep -v '^${{ inputs.exclude }}/' || true)
        echo "changed_files<<EOF" >> $GITHUB_OUTPUT
        echo "$CHANGED_FILES" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

        if [ -z "$CHANGED_FILES" ]; then
          echo "has_changes=false" >> $GITHUB_OUTPUT
        else
          echo "has_changes=true" >> $GITHUB_OUTPUT
        fi

    - name: Run clang-tidy analysis
      id: analyze
      shell: bash
      if: steps.changed-files.outputs.has_changes == 'true'
      run: |
        COMMENTS_FILE=$(mktemp)
        TOTAL_ISSUES=0

        while IFS= read -r file; do
          if [ -n "$file" ] && [ -f "$file" ]; then
            echo "Analyzing $file..."
            if clang-tidy-${{ inputs.clang_tidy_version }} "$file" \
               -p ${{ inputs.build_dir }} --format-style=file 2>&1 | \
               tee -a "$COMMENTS_FILE"; then
              ISSUES=$(grep -c "warning:\|error:" "$COMMENTS_FILE" || echo "0")
              TOTAL_ISSUES=$((TOTAL_ISSUES + ISSUES))
            else
              echo "::error::Failed to analyze $file"
              TOTAL_ISSUES=$((TOTAL_ISSUES + 1))
            fi
          fi
        done <<< "${{ steps.changed-files.outputs.changed_files }}"

        echo "total_comments=$TOTAL_ISSUES" >> $GITHUB_OUTPUT

        if [ -f "$COMMENTS_FILE" ] && [ -s "$COMMENTS_FILE" ]; then
          echo "::group::Clang-tidy Analysis Results"
          cat "$COMMENTS_FILE"
          echo "::endgroup::"
        fi

        if [ "$TOTAL_ISSUES" -gt 0 ]; then
          echo "::error::Found $TOTAL_ISSUES clang-tidy issues"
        else
          echo "No clang-tidy issues found"
        fi

    - name: Set output for no changes
      shell: bash
      if: steps.changed-files.outputs.has_changes == 'false'
      run: |
        echo "total_comments=0" >> $GITHUB_OUTPUT
