name: Build application

on: [push, pull_request]

jobs:
  ubuntu-gcc-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup environment
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt-get update
        sudo apt-get install gcc-12 g++-12
        sudo apt-get install cppcheck ninja-build
        sudo apt-get install mpich libmpich* mpi* openmpi-bin
        sudo apt-get install libomp-dev
        sudo apt-get install valgrind
    - name: Update submodules
      run: git submodule update --init --recursive
    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
          key: ${{ github.job }}
          create-symlink: true
    - name: CMake configure
      run: |
        mkdir build
        cd build
        cmake -D CMAKE_C_COMPILER_LAUNCHER=ccache -D CMAKE_CXX_COMPILER_LAUNCHER=ccache -G Ninja -D USE_SEQ=ON -D USE_MPI=ON -D USE_OMP=ON -D USE_TBB=ON -D USE_STD=ON -D CMAKE_BUILD_TYPE=RELEASE ..
        cd ..
      env:
        CC: gcc-12
        CXX: g++-12
    - name: Ninja build
      run: |
        cd build
        ninja
        cd ..
      env:
        CC: gcc-12
        CXX: g++-12
    - name: Run tests
      run: |
        export OMP_NUM_THREADS=4
        source scripts/run.sh
  ubuntu-clang-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup environment
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt-get update
        sudo apt-get install clang-15
        sudo apt-get install cppcheck ninja-build
        sudo apt-get install mpich libmpich* mpi* openmpi-bin
        sudo apt-get install libomp-15-dev
        sudo apt-get install python3-pip
        sudo apt-get install valgrind
    - name: Update submodules
      run: git submodule update --init --recursive
    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
          key: ${{ github.job }}
          create-symlink: true
    - name: CMake configure
      run: |
        mkdir build
        cd build
        cmake -D CMAKE_C_COMPILER_LAUNCHER=ccache -D CMAKE_CXX_COMPILER_LAUNCHER=ccache -G Ninja -D USE_SEQ=ON -D USE_MPI=ON -D USE_OMP=ON -D USE_TBB=ON -D USE_STD=ON -D CMAKE_BUILD_TYPE=RELEASE ..
        cd ..
      env:
        CC: clang-15
        CXX: clang++-15
    - name: Ninja build
      run: |
        cd build
        ninja
        cd ..
      env:
        CC: clang-15
        CXX: clang++-15
    - name: Run tests
      run: |
        export OMP_NUM_THREADS=4
        source scripts/run.sh
  macos-clang-build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup environment
      run: |
        brew update-reset
        brew install cppcheck ninja mpich llvm
        brew install libomp
        brew link libomp --overwrite --force
        brew install openssl
        brew link openssl --overwrite --force
    - name: Update submodules
      run: git submodule update --init --recursive
    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
          key: ${{ github.job }}
          create-symlink: true
    - name: CMake configure
      run: |
        mkdir build
        cd build
        cmake -D CMAKE_C_COMPILER_LAUNCHER=ccache -D CMAKE_CXX_COMPILER_LAUNCHER=ccache -G Ninja -D USE_SEQ=ON -D USE_MPI=OFF -D USE_OMP=ON -D USE_TBB=ON -D USE_STD=ON -D CMAKE_BUILD_TYPE=RELEASE \
          -DCMAKE_C_FLAGS="-I$(brew --prefix)/opt/libomp/include" \
          -DCMAKE_CXX_FLAGS="-I$(brew --prefix)/opt/libomp/include" ..
    - name: Ninja build
      run: |
        cd build
        ninja
        cd ..
    - name: Run tests
      run: |
        export OMP_NUM_THREADS=4
        source scripts/run_mac.sh
  windows-msvc-build:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v1
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
    - name: Setup MPI
      uses: mpi4py/setup-mpi@v1
      with:
        mpi: msmpi
    - name: Download dependencies
      run: |
        choco install openssl
    - name: Update submodules
      run: git submodule update --init --recursive
    - name: Setup ccache
      uses: Chocobo1/setup-ccache-action@v1
      with:
        windows_compile_environment: msvc
    - name: CMake configure
      shell: bash
      run: |
        mkdir build
        cd build 
        cmake -D CMAKE_C_COMPILER_LAUNCHER=ccache -D CMAKE_CXX_COMPILER_LAUNCHER=ccache -D USE_SEQ=ON -D USE_MPI=ON -D USE_OMP=ON -D USE_TBB=OFF -D USE_STD=ON -D CMAKE_BUILD_TYPE=RELEASE ..
        cd ..
    - name: MSBuild
      shell: bash
      run: |
        cd build
        cmake --build . --config Release --parallel
        cd ..
    - name: Run tests
      run: |
        set OMP_NUM_THREADS=4
        scripts/run.bat
