name: Pages

on:
  push:
    paths:
      - "docs/**"
      - "scoreboard/**"
      - ".github/workflows/pages.yml"
  pull_request:
    paths:
      - "docs/**"
      - "scoreboard/**"
      - ".github/workflows/pages.yml"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  pages: write

jobs:
  build-sphinx:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        working-directory: ./docs
        run: |
          python3 -m pip install -r requirements.txt
      - name: Build i18n
        working-directory: ./docs
        run: |
          make gettext
          sphinx-build -b gettext . _build/gettext
          sphinx-intl update -p _build/gettext -l en -l ru
      - name: Build documentation
        working-directory: ./docs
        run: |
          make html
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sphinx-documentation
          path: ./docs/_build/html
  build-scoreboard:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          python3 -m pip install -r requirements.txt
      - name: Build scoreboard
        run: |
          python3 scoreboard/main.py
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: scoreboard
          path: ./scoreboard/
  deploy-pages:
    if: github.ref == 'refs/heads/master'
    needs:
      - build-sphinx
      - build-scoreboard
    runs-on: ubuntu-24.04
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: sphinx-documentation
          path: ./
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: scoreboard
          path: ./scoreboard/
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
