name: Pre-commit checks

on:
  push:
  pull_request:
  workflow_call:

jobs:
  pre-commit:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Setup environment
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y \
            gcc-14 g++-14 ninja-build python3-pip
          wget https://apt.llvm.org/llvm.sh
          chmod u+x llvm.sh
          sudo ./llvm.sh 20 all
          python3 -m pip install -r requirements.txt
      - name: Run pre-commit checks
        run: |
          FROM_REF="${{ github.base_ref || 'HEAD~1' }}"
          git fetch origin $FROM_REF:$FROM_REF || true
          pre-commit run --from-ref $FROM_REF --to-ref HEAD
