name: Shell Lint

on:
  workflow_call:
  push:
    paths:
      - '**/*.sh'
      - '.github/workflows/shell-lint.yml'
  pull_request:
    paths:
      - '**/*.sh'
      - '.github/workflows/shell-lint.yml'

jobs:
  shell-lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Install shellcheck
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck
      - name: Run shellcheck
        run: shellcheck scripts/*.sh
