name: Static analysis

on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: >-
    ${{ github.ref != 'refs/heads/master' &&
        github.event_name != 'merge_group' &&
        !startsWith(github.ref, 'refs/heads/gh-readonly-queue') }}

jobs:
  clang-tidy:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ runner.os }}-clang
      - uses: ZedThree/clang-tidy-review@v0.21.0
        id: review
        with:
          build_dir: build
          apt_packages: openmpi-bin,openmpi-common,libopenmpi-dev,ninja-build,libomp-19-dev,valgrind
          cmake_command: >
            cmake -S . -B build -G Ninja
            -D CMAKE_C_COMPILER_LAUNCHER=ccache -D CMAKE_CXX_COMPILER_LAUNCHER=ccache
            -D CMAKE_BUILD_TYPE=RELEASE -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
          exclude: 3rdparty
          clang_tidy_checks: ""
          split_workflow: true
          clang_tidy_version: "19"
          lgtm_comment_body: ""
        env:
          CC: clang-19
          CXX: clang++-19
      - if: steps.review.outputs.total_comments > 0
        run: |
          echo "clang-tidy run has failed. See previous 'Run clang-tidy' stage logs"
          exit 1
  clang-tidy-for-gcc-build:
    needs:
      - clang-tidy
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ runner.os }}-gcc
      - uses: ZedThree/clang-tidy-review@v0.21.0
        id: review
        with:
          build_dir: build
          apt_packages: openmpi-bin,openmpi-common,libopenmpi-dev,ninja-build,libomp-19-dev,valgrind
          cmake_command: >
            cmake -S . -B build -G Ninja
            -D CMAKE_C_COMPILER_LAUNCHER=ccache -D CMAKE_CXX_COMPILER_LAUNCHER=ccache
            -D CMAKE_BUILD_TYPE=RELEASE -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
          exclude: 3rdparty
          clang_tidy_checks: ""
          split_workflow: true
          clang_tidy_version: "19"
          lgtm_comment_body: ""
      - if: steps.review.outputs.total_comments > 0
        run: |
          echo "clang-tidy run has failed. See previous 'Run clang-tidy' stage logs"
          exit 1
  nolint-check:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Search for linter suppression markers
        run: |
          export BASE_REF=${{ github.event.pull_request.base.ref }}
          export CHANGED_FILES="$(git diff --name-only origin/$BASE_REF HEAD | grep '^tasks/')"
          if [ -z "$CHANGED_FILES" ]; then
            echo "No changed files in tasks directory."
            exit 0
          fi
          for file in $CHANGED_FILES; do
            if grep -n "NOLINT" "$file"; then
              echo "::error::Found 'NOLINT' in $file."
              exit 1
            fi
            if grep -En 'IWYU[[:space:]]+pragma' "$file"; then
              echo "::error::Found 'IWYU pragma' in $file."
              exit 1
            fi
          done
          echo "No linter suppression markers found in changed files."
